services:
  # NATS JetStream Cluster
  n1:
    container_name: n1
    image: nats:latest
    entrypoint: /nats-server
    command: --name N1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245,nats://n3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4222:4222
    volumes:
      - ./jetstream-cluster/n1:/data
  n2:
    container_name: n2
    image: nats:latest
    entrypoint: /nats-server
    command: --name N2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245,nats://n3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4223:4222
    volumes:
      - ./jetstream-cluster/n2:/data
    depends_on:
      - n1
  n3:
    container_name: n3
    image: nats:latest
    entrypoint: /nats-server
    command: --name N3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245,nats://n3:4245 -p 4222
    networks:
      - nats
    ports:
      - 4224:4222
    volumes:
      - ./jetstream-cluster/n3:/data
    depends_on:
      - n1
      - n2
  # Pull API
  pull-api:
    image: node:lts-alpine
    container_name: pull-api
    user: node
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app
    command: npm run dev
    networks:
      - nats
    depends_on:
      - n1
      - n2
      - n3
networks:
  nats: {}