services:
  # Publish API
  publisher-api:
    image: node:lts-alpine
    container_name: publlisher-api
    user: node
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./publisher:/home/node/app
    command: npm run dev
    environment:
      API_KEY: 'api key to be used for each message'
    networks:
      - nats
networks:
  nats:
    external:
      name: nats